### ISSUE TITLE
armv8设备安装docker一键脚本出错

### ISSUE THREAD

**Issue by dorccl4k** [sec-an/TV_Spider#10]
Step 4/5 : RUN pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ -r /TV/requirements.txt     && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
 ---> Running in f2e33eb99f1a
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938a9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938a9180>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938aa7a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938ab3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938a90c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/
ERROR: Could not find a version that satisfies the requirement flask (from versions: none)
ERROR: No matching distribution found for flask
WARNING: There was an error checking the latest version of pip.
The command '/bin/sh -c pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ -r /TV/requirements.txt     && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone' returned a non-zero code: 1
Error response from daemon: No such container: TV-Spider
Error: failed to start containers: TV-Spider
更新完成。

**Comment by sec-an** [comment]
> Step 4/5 : RUN pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ -r /TV/requirements.txt && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone ---> Running in f2e33eb99f1a Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/ WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938a9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938a9180>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938aa7a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938ab3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff938a90c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/flask/ ERROR: Could not find a version that satisfies the requirement flask (from versions: none) ERROR: No matching distribution found for flask WARNING: There was an error checking the latest version of pip. The command '/bin/sh -c pip install -i https://pypi.mirrors.ustc.edu.cn/simple/ -r /TV/requirements.txt && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone' returned a non-zero code: 1 Error response from daemon: No such container: TV-Spider Error: failed to start containers: TV-Spider 更新完成。

应该是和pypi镜像源的链接出了问题，检查一下你的网络环境或者更换镜像源试试
