### ISSUE TITLE
能否完善下宝塔安装，后两项的步骤图文说明

### ISSUE THREAD

**Issue by zjwywt** [sec-an/TV_Spider#3]
域名映射和端口成功，但还是不能进入页面。另外按照您提供的方法，用www用户运行不成功，需要切换至root用户才能正常运行。

**Comment by cn0068** [comment]
我也是按图文说明安装的，安装过程未提示错误。也放行了端口。但不能进入页面。不知道什么原因？

**Comment by zjwywt** [comment]
> 我也是按图文说明安装的，安装过程未提示错误。也放行了端口。但不能进入页面。不知道什么原因？ [2022-08-24 22:48:11 +0800] [2268625] [CRITICAL] WORKER TIMEOUT (pid:2273305) [2022-08-24 22:48:11 +0800] [2273305] [INFO] Worker exiting (pid: 2273305) [2022-08-24 22:48:11 +0800] [2273351] [INFO] Booting worker with pid: 2273351 [2022-08-24 22:48:12 +0800] [2273351] [ERROR] Exception in worker process Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo return self.pool.apply(_socket.getaddrinfo, args, kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/pool.py", line 161, in apply return self.spawn(func, *args, **kwds).get() File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/_compat.py", line 65, in reraise raise value.with_traceback(tb) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/threadpool.py", line 167, in __run_task thread_result.set(func(*args, **kwargs)) socket.gaierror: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn conn.connect() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect self.sock = conn = self._new_conn() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f563320f520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f563320f520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker worker.init_process() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process super().init_process() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi = self.app.wsgi() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load return self.load_wsgiapp() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp return util.import_app(self.app_uri) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app mod = importlib.import_module(module) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/www/wwwroot/TV_Spider/app.py", line 2, in from spider import * File "/www/wwwroot/TV_Spider/spider/**init**.py", line 3, in from .gitcafe import * File "/www/wwwroot/TV_Spider/spider/gitcafe.py", line 4, in from utils import ali File "/www/wwwroot/TV_Spider/utils/ali.py", line 8, in ali = Aligo(refresh_token=Token) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/apis/Aligo.py", line 105, in **init** super().**init**( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/core/BaseAligo.py", line 48, in **init** self._auth: Auth = Auth( # type: ignore File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/core/Auth.py", line 165, in **init** self._refresh_token(refresh_token) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/core/Auth.py", line 259, in _refresh_token response = self.session.post( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/sessions.py", line 635, in post return self.request("POST", url, data=data, json=json, **kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f563320f520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) [2022-08-24 22:48:12 +0800] [2273351] [INFO] Worker exiting (pid: 2273351) [2022-08-24 22:48:12 +0800] [2268625] [INFO] Shutting down: Master [2022-08-24 22:48:12 +0800] [2268625] [INFO] Reason: Worker failed to boot.

你这个把www用户改成root用户运行，就可以了，

**Comment by cn0068** [comment]
> > 我也是按图文说明安装的，安装过程未提示错误。也放行了端口。但不能进入页面。不知道什么原因？ [2022-08-24 22:48:11 +0800] [2268625] [CRITICAL] WORKER TIMEOUT (pid:2273305) [2022-08-24 22:48:11 +0800] [2273305] [INFO] Worker exiting (pid: 2273305) [2022-08-24 22:48:11 +0800] [2273351] [INFO] Booting worker with pid: 2273351 [2022-08-24 22:48:12 +0800] [2273351] [ERROR] Exception in worker process Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn conn = connection.create_connection( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo return self.pool.apply(_socket.getaddrinfo, args, kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/pool.py", line 161, in apply return self.spawn(func, *args, **kwds).get() File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/_compat.py", line 65, in reraise raise value.with_traceback(tb) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gevent/threadpool.py", line 167, in __run_task thread_result.set(func(*args, **kwargs)) socket.gaierror: [Errno -3] Temporary failure in name resolution
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request self._validate_conn(conn) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn conn.connect() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect self.sock = conn = self._new_conn() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn raise NewConnectionError( urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f563320f520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f563320f520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last): File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker worker.init_process() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process super().init_process() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi = self.app.wsgi() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load return self.load_wsgiapp() File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp return util.import_app(self.app_uri) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app mod = importlib.import_module(module) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/www/wwwroot/TV_Spider/app.py", line 2, in from spider import * File "/www/wwwroot/TV_Spider/spider/**init**.py", line 3, in from .gitcafe import * File "/www/wwwroot/TV_Spider/spider/gitcafe.py", line 4, in from utils import ali File "/www/wwwroot/TV_Spider/utils/ali.py", line 8, in ali = Aligo(refresh_token=Token) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/apis/Aligo.py", line 105, in **init** super().**init**( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/core/BaseAligo.py", line 48, in **init** self._auth: Auth = Auth( # type: ignore File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/core/Auth.py", line 165, in **init** self._refresh_token(refresh_token) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/aligo/core/Auth.py", line 259, in _refresh_token response = self.session.post( File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/sessions.py", line 635, in post return self.request("POST", url, data=data, json=json, **kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/sessions.py", line 587, in request resp = self.send(prep, **send_kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/sessions.py", line 701, in send r = adapter.send(request, **kwargs) File "/www/wwwroot/TV_Spider/937d34c3e8909e013e178b67314b3cf0_venv/lib/python3.9/site-packages/requests/adapters.py", line 565, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.aliyundrive.com', port=443): Max retries exceeded with url: /v2/account/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f563320f520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) [2022-08-24 22:48:12 +0800] [2273351] [INFO] Worker exiting (pid: 2273351) [2022-08-24 22:48:12 +0800] [2268625] [INFO] Shutting down: Master [2022-08-24 22:48:12 +0800] [2268625] [INFO] Reason: Worker failed to boot.
> 
> 你这个把www用户改成root用户运行，就可以了，

我重新安装改成root用户一样的错误。
