### ISSUE TITLE
用函数的结果反馈比服务器慢好几秒，另外盘搜可以搜到，打开是空白

### ISSUE THREAD

**Issue by dabbing2019** [sec-an/TV_Spider#8]
试了好多，盘搜搜到，打开就是空白
token和服务器t4用的一样，服务器是正常的

**Comment by sec-an** [comment]
1. 函数比服务器慢基本上是一定的，函数需要冷启动时间
2. 可能是内存分配不够，建议暂时打开云函数的日志服务，看一下请求时的日志是否有报错等，测试的时候是都可以正常播放的

**Comment by sec-an** [comment]
> 试了好多，盘搜搜到，打开就是空白 token和服务器t4用的一样，服务器是正常的

1. 函数比服务器慢基本上是一定的，函数需要冷启动时间
2. 可能是内存分配不够，建议暂时打开云函数的日志服务，看一下请求时的日志是否有报错等，测试的时候是都可以正常播放的
