### ISSUE TITLE
json如何配置在TVBoxOSC中

### ISSUE THREAD

**Issue by songkunhuang** [sec-an/TV_Spider#9]
给出了json使用示例，请问如何配置在TVBoxOSC客户端中？

**Comment by sec-an** [comment]
> 给出了json使用示例，请问如何配置在TVBoxOSC客户端中？

通过配置在线地址或者本地文件…
可以参考[猫影视TV配置编辑器](https://catvodtvofficial.github.io/CatVodTVJsonEditor/)
